// frontend/src/core/widgets/button/button.vue
<script setup lang="ts">
import { cn } from "@/core/utils";
import { buttonVariants } from "@/ui/button/button.config";
import { computed } from "vue";

interface Props {
  variant?: NonNullable<Parameters<typeof buttonVariants>[0]>["variant"];
  size?: NonNullable<Parameters<typeof buttonVariants>[0]>["size"];
  as?: string;
}

const props = withDefaults(defineProps<Props>(), {
  as: "button",
});

const classes = computed(() => {
  return buttonVariants({ variant: props.variant, size: props.size });
});
</script>

<template>
  <component
    :is="as"
    :class="cn(classes)"
    >
    <slot />
  </component>
</template>

// frontend/src/core/widgets/button/button.tsx
import { cn } from "@/core/utils";
import { buttonVariants } from "@/ui/button/button.config";
import { Slot } from "@radix-ui/react-slot";
import type { VariantProps } from "class-variance-authority";
import type React from "react";

function Button({
	className,
	variant,
	size,
	asChild = false,
	...props
}: React.ComponentProps<"button"> &
	VariantProps<typeof buttonVariants> & {
		asChild?: boolean;
	}) {
	const Comp = asChild ? Slot : "button";

	return (
		<>
			<Comp
				data-slot="button"
				className={cn(buttonVariants({ variant, size, className }))}
				{...props}
			/>
		</>
	);
}

export { Button, buttonVariants };
